### ISSUE TITLE
Can't add more Custom endpoints in Azure Iot Hub

### ISSUE THREAD

**Issue by Ilheu** [Azure/iot#5]
Hi, I can't add more than one routing custom endpoint, can you help me ?
![image](https://user-images.githubusercontent.com/8053606/54606634-4a856b00-4a44-11e9-8af9-4f9baab529d1.png)

**Comment by bp274** [comment]
You must be using an IoT hub in the free tier. The free tier only allows you to set one endpoint. For multiple endpoints use an IoT hub in a paid tier

**Comment by ufalak** [comment]
Thats not specified in docs!

**Comment by ryanwinter** [comment]
Close as not directly related to awesome site.
