### ISSUE TITLE
Document restrictions when communicating from device with HTTP

### ISSUE THREAD

**Issue by MatthewDavidCampbell** [Azure/iot#6]
The IoT Rest is clear what functions are available to a device when communicating over HTTP (see https://docs.microsoft.com/rest/api/iothub/).  Messaging, file uploads and sending events are documented well when using the device policy.  One thing that is baffling is that with the device policy it is not possible to receive twin properties.   It is supported via the Rest interface but only with the service policy or higher.  It is less clear when reading the Device Guide (see https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins) that grabbing twin information is impossible through HTTP.

Seems strange that the device policy for the HTTP protocol can't receive or send twin properties (i.e. a basic function for a device) but with the SDK (over MQTT).  There is a disclaimer in the Device Guide:

    This description is useful only if the device app cannot use any of Azure IoT device SDKs and must program the MQTT interface directly

What is the thinking here?  Why bottleneck HTTP?  We have devices on old Win 98 | NT machines that can't deal with MQTT or AMQP (i.e. restricted to Net 3.5).  Here HTTP is our only option.  But we don't want a service policy on a device just to make reasonable twin property calls (i.e. receive | send desired respective reported).

**Comment by ryanwinter** [comment]
Closing as not directly related to awesome site.
